apiVersion: v1
kind: Service
metadata:
  name: operational-assistant-svc
  namespace: operational-assistant
  labels:
    app: operational-assistant
spec:
  selector:
    app: operational-assistant
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
